/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include "shared_types.h"

GType thrift_shared_struct_get_type (void)
{
    static GType type = 0;

    if (type == 0) 
    {
        static const GTypeInfo type_info = 
        {
            sizeof (ThriftSharedStructClass),
            NULL, /* base_init */
            NULL, /* base_finalize */
            NULL, /* class_init */
            NULL, /* class_finalize */
            NULL, /* class_data */
            sizeof (ThriftSharedStruct),
            0, /* n_preallocs */
            thrift_shared_struct_instance_init /* instance_init */
        };

        type = g_type_register_static (G_TYPE_OBJECT, 
            "ThriftSharedStructType", /* type name as string */
            &type_info, 0);
    }

    return type;
}
void thrift_shared_struct_instance_init (GTypeInstance *instance, gpointer g_class) {
    ThriftSharedStruct * this = THRIFT_SHARED_STRUCT_(instance);
    this->key = 0;
    this->value = "";
}
