/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef thrudoc_H
#define thrudoc_H

#include "thrift_client.h"
#include "thrudoc_types.h"

typedef struct _ThriftThrudocClient ThriftThrudocClient;
struct _ThriftThrudocClient
{
  ThriftClient parent;
};
typedef struct _ThriftThrudocClientClass ThriftThrudocClientClass;
struct _ThriftThrudocClientClass
{
  ThriftClientClass parent;

};

void thrift_thrudoc_get_buckets (ThriftThrudocClient * client, GPtrArray ** _return);
void thrift_thrudoc_send_get_buckets (ThriftThrudocClient * client);
void thrift_thrudoc_recv_get_buckets (ThriftThrudocClient * client, GPtrArray ** _return);
void thrift_thrudoc_put (ThriftThrudocClient * client, const gchar * bucket, const gchar * key, const gchar * value);
void thrift_thrudoc_send_put (ThriftThrudocClient * client, const gchar * bucket, const gchar * key, const gchar * value);
void thrift_thrudoc_recv_put (ThriftThrudocClient * client);
void thrift_thrudoc_get (ThriftThrudocClient * client, gchar ** _return, const gchar * bucket, const gchar * key);
void thrift_thrudoc_send_get (ThriftThrudocClient * client, const gchar * bucket, const gchar * key);
void thrift_thrudoc_recv_get (ThriftThrudocClient * client, gchar ** _return);
void thrift_thrudoc_remove (ThriftThrudocClient * client, const gchar * bucket, const gchar * key);
void thrift_thrudoc_send_remove (ThriftThrudocClient * client, const gchar * bucket, const gchar * key);
void thrift_thrudoc_recv_remove (ThriftThrudocClient * client);
void thrift_thrudoc_put_value (ThriftThrudocClient * client, gchar ** _return, const gchar * bucket, const gchar * value);
void thrift_thrudoc_send_put_value (ThriftThrudocClient * client, const gchar * bucket, const gchar * value);
void thrift_thrudoc_recv_put_value (ThriftThrudocClient * client, gchar ** _return);
void thrift_thrudoc_scan (ThriftThrudocClient * client, ThriftThrudocScanResponse ** _return, const gchar * bucket, const gchar * seed, const gint32 count);
void thrift_thrudoc_send_scan (ThriftThrudocClient * client, const gchar * bucket, const gchar * seed, const gint32 count);
void thrift_thrudoc_recv_scan (ThriftThrudocClient * client, ThriftThrudocScanResponse ** _return);
void thrift_thrudoc_put_list (ThriftThrudocClient * client, GPtrArray ** _return, const GPtrArray * elements);
void thrift_thrudoc_send_put_list (ThriftThrudocClient * client, const GPtrArray * elements);
void thrift_thrudoc_recv_put_list (ThriftThrudocClient * client, GPtrArray ** _return);
void thrift_thrudoc_get_list (ThriftThrudocClient * client, GPtrArray ** _return, const GPtrArray * elements);
void thrift_thrudoc_send_get_list (ThriftThrudocClient * client, const GPtrArray * elements);
void thrift_thrudoc_recv_get_list (ThriftThrudocClient * client, GPtrArray ** _return);
void thrift_thrudoc_remove_list (ThriftThrudocClient * client, GPtrArray ** _return, const GPtrArray * elements);
void thrift_thrudoc_send_remove_list (ThriftThrudocClient * client, const GPtrArray * elements);
void thrift_thrudoc_recv_remove_list (ThriftThrudocClient * client, GPtrArray ** _return);
void thrift_thrudoc_put_value_list (ThriftThrudocClient * client, GPtrArray ** _return, const GPtrArray * elements);
void thrift_thrudoc_send_put_value_list (ThriftThrudocClient * client, const GPtrArray * elements);
void thrift_thrudoc_recv_put_value_list (ThriftThrudocClient * client, GPtrArray ** _return);
void thrift_thrudoc_admin (ThriftThrudocClient * client, gchar ** _return, const gchar * op, const gchar * data);
void thrift_thrudoc_send_admin (ThriftThrudocClient * client, const gchar * op, const gchar * data);
void thrift_thrudoc_recv_admin (ThriftThrudocClient * client, gchar ** _return);

#endif /* thrudoc_H */
