/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "thrudoc.h"

void thrift_thrudoc_get_buckets (ThriftThrudocClient * client, GPtrArray ** _return)
{
  thrift_thrudoc_send_get_buckets (client);
  thrift_thrudoc_recv_get_buckets (client, _return);
}

void thrift_thrudoc_send_get_buckets (ThriftThrudocClient * client)
{
  gint32 cseqid = 0;
  ThriftProtocol * thrift_protocol = THRIFT_CLIENT (client)->thrift_protocol;

  thrift_protocol_write_message_begin (thrift_protocol, "getBuckets", T_CALL, cseqid);

  Thrudoc_getBuckets_pargs args;
  args.write(oprot_);

  thrift_protocol_write_message_end (thrift_protocol);
}

void thrift_thrudoc_recv_get_buckets (ThriftThrudocClient * client, GPtrArray ** _return)
{
}

void thrift_thrudoc_put (ThriftThrudocClient * client, const gchar * bucket, const gchar * key, const gchar * value)
{
  thrift_thrudoc_send_put (client, bucket, key, value);
  thrift_thrudoc_recv_put (client);
}

void thrift_thrudoc_send_put (ThriftThrudocClient * client, const gchar * bucket, const gchar * key, const gchar * value)
{
  gint32 cseqid = 0;
  ThriftProtocol * thrift_protocol = THRIFT_CLIENT (client)->thrift_protocol;

  thrift_protocol_write_message_begin (thrift_protocol, "put", T_CALL, cseqid);

  Thrudoc_put_pargs args;
  args.bucket = &bucket;
  args.key = &key;
  args.value = &value;
  args.write(oprot_);

  thrift_protocol_write_message_end (thrift_protocol);
}

void thrift_thrudoc_recv_put (ThriftThrudocClient * client)
{
}

void thrift_thrudoc_get (ThriftThrudocClient * client, gchar ** _return, const gchar * bucket, const gchar * key)
{
  thrift_thrudoc_send_get (client, bucket, key);
  thrift_thrudoc_recv_get (client, _return);
}

void thrift_thrudoc_send_get (ThriftThrudocClient * client, const gchar * bucket, const gchar * key)
{
  gint32 cseqid = 0;
  ThriftProtocol * thrift_protocol = THRIFT_CLIENT (client)->thrift_protocol;

  thrift_protocol_write_message_begin (thrift_protocol, "get", T_CALL, cseqid);

  Thrudoc_get_pargs args;
  args.bucket = &bucket;
  args.key = &key;
  args.write(oprot_);

  thrift_protocol_write_message_end (thrift_protocol);
}

void thrift_thrudoc_recv_get (ThriftThrudocClient * client, gchar ** _return)
{
}

void thrift_thrudoc_remove (ThriftThrudocClient * client, const gchar * bucket, const gchar * key)
{
  thrift_thrudoc_send_remove (client, bucket, key);
  thrift_thrudoc_recv_remove (client);
}

void thrift_thrudoc_send_remove (ThriftThrudocClient * client, const gchar * bucket, const gchar * key)
{
  gint32 cseqid = 0;
  ThriftProtocol * thrift_protocol = THRIFT_CLIENT (client)->thrift_protocol;

  thrift_protocol_write_message_begin (thrift_protocol, "remove", T_CALL, cseqid);

  Thrudoc_remove_pargs args;
  args.bucket = &bucket;
  args.key = &key;
  args.write(oprot_);

  thrift_protocol_write_message_end (thrift_protocol);
}

void thrift_thrudoc_recv_remove (ThriftThrudocClient * client)
{
}

void thrift_thrudoc_put_value (ThriftThrudocClient * client, gchar ** _return, const gchar * bucket, const gchar * value)
{
  thrift_thrudoc_send_put_value (client, bucket, value);
  thrift_thrudoc_recv_put_value (client, _return);
}

void thrift_thrudoc_send_put_value (ThriftThrudocClient * client, const gchar * bucket, const gchar * value)
{
  gint32 cseqid = 0;
  ThriftProtocol * thrift_protocol = THRIFT_CLIENT (client)->thrift_protocol;

  thrift_protocol_write_message_begin (thrift_protocol, "putValue", T_CALL, cseqid);

  Thrudoc_putValue_pargs args;
  args.bucket = &bucket;
  args.value = &value;
  args.write(oprot_);

  thrift_protocol_write_message_end (thrift_protocol);
}

void thrift_thrudoc_recv_put_value (ThriftThrudocClient * client, gchar ** _return)
{
}

void thrift_thrudoc_scan (ThriftThrudocClient * client, ThriftThrudocScanResponse ** _return, const gchar * bucket, const gchar * seed, const gint32 count)
{
  thrift_thrudoc_send_scan (client, bucket, seed, count);
  thrift_thrudoc_recv_scan (client, _return);
}

void thrift_thrudoc_send_scan (ThriftThrudocClient * client, const gchar * bucket, const gchar * seed, const gint32 count)
{
  gint32 cseqid = 0;
  ThriftProtocol * thrift_protocol = THRIFT_CLIENT (client)->thrift_protocol;

  thrift_protocol_write_message_begin (thrift_protocol, "scan", T_CALL, cseqid);

  Thrudoc_scan_pargs args;
  args.bucket = &bucket;
  args.seed = &seed;
  args.count = &count;
  args.write(oprot_);

  thrift_protocol_write_message_end (thrift_protocol);
}

void thrift_thrudoc_recv_scan (ThriftThrudocClient * client, ThriftThrudocScanResponse ** _return)
{
}

void thrift_thrudoc_put_list (ThriftThrudocClient * client, GPtrArray ** _return, const GPtrArray * elements)
{
  thrift_thrudoc_send_put_list (client, elements);
  thrift_thrudoc_recv_put_list (client, _return);
}

void thrift_thrudoc_send_put_list (ThriftThrudocClient * client, const GPtrArray * elements)
{
  gint32 cseqid = 0;
  ThriftProtocol * thrift_protocol = THRIFT_CLIENT (client)->thrift_protocol;

  thrift_protocol_write_message_begin (thrift_protocol, "putList", T_CALL, cseqid);

  Thrudoc_putList_pargs args;
  args.elements = &elements;
  args.write(oprot_);

  thrift_protocol_write_message_end (thrift_protocol);
}

void thrift_thrudoc_recv_put_list (ThriftThrudocClient * client, GPtrArray ** _return)
{
}

void thrift_thrudoc_get_list (ThriftThrudocClient * client, GPtrArray ** _return, const GPtrArray * elements)
{
  thrift_thrudoc_send_get_list (client, elements);
  thrift_thrudoc_recv_get_list (client, _return);
}

void thrift_thrudoc_send_get_list (ThriftThrudocClient * client, const GPtrArray * elements)
{
  gint32 cseqid = 0;
  ThriftProtocol * thrift_protocol = THRIFT_CLIENT (client)->thrift_protocol;

  thrift_protocol_write_message_begin (thrift_protocol, "getList", T_CALL, cseqid);

  Thrudoc_getList_pargs args;
  args.elements = &elements;
  args.write(oprot_);

  thrift_protocol_write_message_end (thrift_protocol);
}

void thrift_thrudoc_recv_get_list (ThriftThrudocClient * client, GPtrArray ** _return)
{
}

void thrift_thrudoc_remove_list (ThriftThrudocClient * client, GPtrArray ** _return, const GPtrArray * elements)
{
  thrift_thrudoc_send_remove_list (client, elements);
  thrift_thrudoc_recv_remove_list (client, _return);
}

void thrift_thrudoc_send_remove_list (ThriftThrudocClient * client, const GPtrArray * elements)
{
  gint32 cseqid = 0;
  ThriftProtocol * thrift_protocol = THRIFT_CLIENT (client)->thrift_protocol;

  thrift_protocol_write_message_begin (thrift_protocol, "removeList", T_CALL, cseqid);

  Thrudoc_removeList_pargs args;
  args.elements = &elements;
  args.write(oprot_);

  thrift_protocol_write_message_end (thrift_protocol);
}

void thrift_thrudoc_recv_remove_list (ThriftThrudocClient * client, GPtrArray ** _return)
{
}

void thrift_thrudoc_put_value_list (ThriftThrudocClient * client, GPtrArray ** _return, const GPtrArray * elements)
{
  thrift_thrudoc_send_put_value_list (client, elements);
  thrift_thrudoc_recv_put_value_list (client, _return);
}

void thrift_thrudoc_send_put_value_list (ThriftThrudocClient * client, const GPtrArray * elements)
{
  gint32 cseqid = 0;
  ThriftProtocol * thrift_protocol = THRIFT_CLIENT (client)->thrift_protocol;

  thrift_protocol_write_message_begin (thrift_protocol, "putValueList", T_CALL, cseqid);

  Thrudoc_putValueList_pargs args;
  args.elements = &elements;
  args.write(oprot_);

  thrift_protocol_write_message_end (thrift_protocol);
}

void thrift_thrudoc_recv_put_value_list (ThriftThrudocClient * client, GPtrArray ** _return)
{
}

void thrift_thrudoc_admin (ThriftThrudocClient * client, gchar ** _return, const gchar * op, const gchar * data)
{
  thrift_thrudoc_send_admin (client, op, data);
  thrift_thrudoc_recv_admin (client, _return);
}

void thrift_thrudoc_send_admin (ThriftThrudocClient * client, const gchar * op, const gchar * data)
{
  gint32 cseqid = 0;
  ThriftProtocol * thrift_protocol = THRIFT_CLIENT (client)->thrift_protocol;

  thrift_protocol_write_message_begin (thrift_protocol, "admin", T_CALL, cseqid);

  Thrudoc_admin_pargs args;
  args.op = &op;
  args.data = &data;
  args.write(oprot_);

  thrift_protocol_write_message_end (thrift_protocol);
}

void thrift_thrudoc_recv_admin (ThriftThrudocClient * client, gchar ** _return)
{
}

