/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef Thrudoc_TYPES_H
#define Thrudoc_TYPES_H

/* base includes */
#include <glib-object.h>
#include "thrift_protocol.h"
#include "thrift_struct.h"


/* custom thrift includes */

/* begin types */

typedef enum _ThriftThrudocExceptionType ThriftThrudocExceptionType;
enum _ThriftThrudocExceptionType {
  UNKNOWN = 1,
  NO_SUCH_KEY = 2
};

/* constants */

/* exception */
typedef struct _ThriftThrudocThrudocException ThriftThrudocThrudocException;
struct _ThriftThrudocThrudocException
{ 
    ThriftStruct parent; 

    /* private */
    gchar * what;
    ThriftThrudocExceptionType type;
}; 
typedef struct _ThriftThrudocThrudocExceptionClass ThriftThrudocThrudocExceptionClass;
struct _ThriftThrudocThrudocExceptionClass
{ 
    ThriftStructClass parent; 
}; 
GType thrift_thrudoc_thrudoc_exception_get_type (void);
#define THRIFT_THRUDOC_TYPE_THRUDOC_EXCEPTION (thrift_thrudoc_thrudoc_exception_get_type ())
#define THRIFT_THRUDOC_THRUDOC_EXCEPTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_THRUDOC_TYPE_THRUDOC_EXCEPTION, ThriftThrudocThrudocException))
#define THRIFT_THRUDOC_THRUDOC_EXCEPTION_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT_THRUDOC_TYPE_THRUDOC_EXCEPTION, ThriftThrudocThrudocExceptionClass))
#define THRIFT_THRUDOC_IS_THRUDOC_EXCEPTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_THRUDOC_TYPE_THRUDOC_EXCEPTION))
#define THRIFT_THRUDOC_IS_THRUDOC_EXCEPTION_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_THRUDOC_TYPE_THRUDOC_EXCEPTION))
#define THRIFT_THRUDOC_THRUDOC_EXCEPTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_THRUDOC_TYPE_THRUDOC_EXCEPTION, ThriftThrudocThrudocExceptionClass))

/* struct */
typedef struct _ThriftThrudocElement ThriftThrudocElement;
struct _ThriftThrudocElement
{ 
    ThriftStruct parent; 

    /* private */
    gchar * bucket;
    gchar * key;
    gchar * value;
}; 
typedef struct _ThriftThrudocElementClass ThriftThrudocElementClass;
struct _ThriftThrudocElementClass
{ 
    ThriftStructClass parent; 
}; 
GType thrift_thrudoc_element_get_type (void);
#define THRIFT_THRUDOC_TYPE_ELEMENT (thrift_thrudoc_element_get_type ())
#define THRIFT_THRUDOC_ELEMENT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_THRUDOC_TYPE_ELEMENT, ThriftThrudocElement))
#define THRIFT_THRUDOC_ELEMENT_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT_THRUDOC_TYPE_ELEMENT, ThriftThrudocElementClass))
#define THRIFT_THRUDOC_IS_ELEMENT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_THRUDOC_TYPE_ELEMENT))
#define THRIFT_THRUDOC_IS_ELEMENT_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_THRUDOC_TYPE_ELEMENT))
#define THRIFT_THRUDOC_ELEMENT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_THRUDOC_TYPE_ELEMENT, ThriftThrudocElementClass))

/* struct */
typedef struct _ThriftThrudocScanResponse ThriftThrudocScanResponse;
struct _ThriftThrudocScanResponse
{ 
    ThriftStruct parent; 

    /* private */
    GPtrArray * elements;
    gchar * seed;
}; 
typedef struct _ThriftThrudocScanResponseClass ThriftThrudocScanResponseClass;
struct _ThriftThrudocScanResponseClass
{ 
    ThriftStructClass parent; 
}; 
GType thrift_thrudoc_scan_response_get_type (void);
#define THRIFT_THRUDOC_TYPE_SCAN_RESPONSE (thrift_thrudoc_scan_response_get_type ())
#define THRIFT_THRUDOC_SCAN_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_THRUDOC_TYPE_SCAN_RESPONSE, ThriftThrudocScanResponse))
#define THRIFT_THRUDOC_SCAN_RESPONSE_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT_THRUDOC_TYPE_SCAN_RESPONSE, ThriftThrudocScanResponseClass))
#define THRIFT_THRUDOC_IS_SCAN_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_THRUDOC_TYPE_SCAN_RESPONSE))
#define THRIFT_THRUDOC_IS_SCAN_RESPONSE_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_THRUDOC_TYPE_SCAN_RESPONSE))
#define THRIFT_THRUDOC_SCAN_RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_THRUDOC_TYPE_SCAN_RESPONSE, ThriftThrudocScanResponseClass))

/* struct */
typedef struct _ThriftThrudocListResponse ThriftThrudocListResponse;
struct _ThriftThrudocListResponse
{ 
    ThriftStruct parent; 

    /* private */
    ThriftThrudocElement * element;
    ThriftThrudocThrudocException * ex;
}; 
typedef struct _ThriftThrudocListResponseClass ThriftThrudocListResponseClass;
struct _ThriftThrudocListResponseClass
{ 
    ThriftStructClass parent; 
}; 
GType thrift_thrudoc_list_response_get_type (void);
#define THRIFT_THRUDOC_TYPE_LIST_RESPONSE (thrift_thrudoc_list_response_get_type ())
#define THRIFT_THRUDOC_LIST_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), THRIFT_THRUDOC_TYPE_LIST_RESPONSE, ThriftThrudocListResponse))
#define THRIFT_THRUDOC_LIST_RESPONSE_CLASS(c) (G_TYPE_CHECK_CLASS_CAST ((c), THRIFT_THRUDOC_TYPE_LIST_RESPONSE, ThriftThrudocListResponseClass))
#define THRIFT_THRUDOC_IS_LIST_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), THRIFT_THRUDOC_TYPE_LIST_RESPONSE))
#define THRIFT_THRUDOC_IS_LIST_RESPONSE_CLASS(c) (G_TYPE_CHECK_CLASS_TYPE ((c), THRIFT_THRUDOC_TYPE_LIST_RESPONSE))
#define THRIFT_THRUDOC_LIST_RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), THRIFT_THRUDOC_TYPE_LIST_RESPONSE, ThriftThrudocListResponseClass))

#endif /* Thrudoc_TYPES_H */
