/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */

#include "tutorial_types.h"

GType thrift_tutorial_work_get_type (void)
{
    static GType type = 0;

    if (type == 0) 
    {
        static const GTypeInfo type_info = 
        {
            sizeof (ThriftTutorialWorkClass),
            NULL, /* base_init */
            NULL, /* base_finalize */
            NULL, /* class_init */
            NULL, /* class_finalize */
            NULL, /* class_data */
            sizeof (ThriftTutorialWork),
            0, /* n_preallocs */
            thrift_tutorial_work_instance_init /* instance_init */
        };

        type = g_type_register_static (G_TYPE_OBJECT, 
            "ThriftTutorialWorkType", /* type name as string */
            &type_info, 0);
    }

    return type;
}
void thrift_tutorial_work_instance_init (GTypeInstance *instance, gpointer g_class) {
    ThriftTutorialWork * this = THRIFT_TUTORIAL_WORK_(instance);
    this->num1 = 42;
    this->num2 = 0;
    this->str1 = "";
    this->str2 = "foo";
}
GType thrift_tutorial_invalid_operation_get_type (void)
{
    static GType type = 0;

    if (type == 0) 
    {
        static const GTypeInfo type_info = 
        {
            sizeof (ThriftTutorialInvalidOperationClass),
            NULL, /* base_init */
            NULL, /* base_finalize */
            NULL, /* class_init */
            NULL, /* class_finalize */
            NULL, /* class_data */
            sizeof (ThriftTutorialInvalidOperation),
            0, /* n_preallocs */
            thrift_tutorial_invalid_operation_instance_init /* instance_init */
        };

        type = g_type_register_static (G_TYPE_OBJECT, 
            "ThriftTutorialInvalidOperationType", /* type name as string */
            &type_info, 0);
    }

    return type;
}
void thrift_tutorial_invalid_operation_instance_init (GTypeInstance *instance, gpointer g_class) {
    ThriftTutorialInvalidOperation * this = THRIFT_TUTORIAL_INVALID_OPERATION_(instance);
    this->what = 0;
    this->why = "";
}
