/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef DebugProtoTest_TYPES_H
#define DebugProtoTest_TYPES_H

#include <Thrift.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>



namespace thrift { namespace test { namespace debug {

class Doubles {
 public:

  static const char* ascii_fingerprint; // = "4B056EA3B3FB01EC41613CEB91B54CE5";
  static const uint8_t binary_fingerprint[16]; // = {0x4B,0x05,0x6E,0xA3,0xB3,0xFB,0x01,0xEC,0x41,0x61,0x3C,0xEB,0x91,0xB5,0x4C,0xE5};

  Doubles() : nan(0), inf(0), neginf(0), repeating(0), big(0), small(0), zero(0), negzero(0) {
  }

  virtual ~Doubles() throw() {}

  static apache::thrift::reflection::local::TypeSpec* local_reflection;

  double nan;
  double inf;
  double neginf;
  double repeating;
  double big;
  double small;
  double zero;
  double negzero;

  struct __isset {
    __isset() : nan(false), inf(false), neginf(false), repeating(false), big(false), small(false), zero(false), negzero(false) {}
    bool nan;
    bool inf;
    bool neginf;
    bool repeating;
    bool big;
    bool small;
    bool zero;
    bool negzero;
  } __isset;

  bool operator == (const Doubles & rhs) const
  {
    if (!(nan == rhs.nan))
      return false;
    if (!(inf == rhs.inf))
      return false;
    if (!(neginf == rhs.neginf))
      return false;
    if (!(repeating == rhs.repeating))
      return false;
    if (!(big == rhs.big))
      return false;
    if (!(small == rhs.small))
      return false;
    if (!(zero == rhs.zero))
      return false;
    if (!(negzero == rhs.negzero))
      return false;
    return true;
  }
  bool operator != (const Doubles &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Doubles & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

// double
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_E8CD7DA078A86726031AD64F35F5A6C0;

// void
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_CAB8111FD0B710A336C898E539090E34;

// {1:double;2:double;3:double;4:double;5:double;6:double;7:double;8:double;}
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_4B056EA3B3FB01EC41613CEB91B54CE5;

class OneOfEach {
 public:

  static const char* ascii_fingerprint; // = "DF7CE78394886179BFAFDB65C5A708BC";
  static const uint8_t binary_fingerprint[16]; // = {0xDF,0x7C,0xE7,0x83,0x94,0x88,0x61,0x79,0xBF,0xAF,0xDB,0x65,0xC5,0xA7,0x08,0xBC};

  OneOfEach() : im_true(0), im_false(0), a_bite(200), integer16(33000), integer32(0), integer64(10000000000LL), double_precision(0), some_characters(""), zomg_unicode(""), what_who(0), base64("") {
    byte_list.push_back(1);
    byte_list.push_back(2);
    byte_list.push_back(3);

    i16_list.push_back(1);
    i16_list.push_back(2);
    i16_list.push_back(3);

    i64_list.push_back(1LL);
    i64_list.push_back(2LL);
    i64_list.push_back(3LL);

  }

  virtual ~OneOfEach() throw() {}

  static apache::thrift::reflection::local::TypeSpec* local_reflection;

  bool im_true;
  bool im_false;
  int8_t a_bite;
  int16_t integer16;
  int32_t integer32;
  int64_t integer64;
  double double_precision;
  std::string some_characters;
  std::string zomg_unicode;
  bool what_who;
  std::string base64;
  std::vector<int8_t>  byte_list;
  std::vector<int16_t>  i16_list;
  std::vector<int64_t>  i64_list;

  struct __isset {
    __isset() : im_true(false), im_false(false), a_bite(false), integer16(false), integer32(false), integer64(false), double_precision(false), some_characters(false), zomg_unicode(false), what_who(false), base64(false), byte_list(false), i16_list(false), i64_list(false) {}
    bool im_true;
    bool im_false;
    bool a_bite;
    bool integer16;
    bool integer32;
    bool integer64;
    bool double_precision;
    bool some_characters;
    bool zomg_unicode;
    bool what_who;
    bool base64;
    bool byte_list;
    bool i16_list;
    bool i64_list;
  } __isset;

  bool operator == (const OneOfEach & rhs) const
  {
    if (!(im_true == rhs.im_true))
      return false;
    if (!(im_false == rhs.im_false))
      return false;
    if (!(a_bite == rhs.a_bite))
      return false;
    if (!(integer16 == rhs.integer16))
      return false;
    if (!(integer32 == rhs.integer32))
      return false;
    if (!(integer64 == rhs.integer64))
      return false;
    if (!(double_precision == rhs.double_precision))
      return false;
    if (!(some_characters == rhs.some_characters))
      return false;
    if (!(zomg_unicode == rhs.zomg_unicode))
      return false;
    if (!(what_who == rhs.what_who))
      return false;
    if (!(base64 == rhs.base64))
      return false;
    if (!(byte_list == rhs.byte_list))
      return false;
    if (!(i16_list == rhs.i16_list))
      return false;
    if (!(i64_list == rhs.i64_list))
      return false;
    return true;
  }
  bool operator != (const OneOfEach &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const OneOfEach & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

// bool
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_C506FF134BABDD6E68AB3E6350E95305;

// byte
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_40EA57D3EE3C07BF1C102B466E1C3091;

// i16
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_2655F23011F3FE4C7C3D757D37D5F9A5;

// i32
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_F89EDB52B075B8BD95989BD3D0A04C0A;

// i64
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_DD1D26230D15C93E8FBDBA07B0299A44;

// string
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_B45CFFE084DD3D20D928BEE85E7B0F21;

// list<byte>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_AA4F7C56251CF3CFAEC27EFC595B8859;

// list<i16>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_9FC1EE2443BBF82A274BA6CB6AEB0BC9;

// list<i64>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_ED613BAC0B5A2A2EBDFC90ADB2CCF9F0;

// {1:bool;2:bool;3:byte;4:i16;5:i32;6:i64;7:double;8:string;9:string;10:bool;11:string;12:list<byte>;13:list<i16>;14:list<i64>;}
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_DF7CE78394886179BFAFDB65C5A708BC;

class Bonk {
 public:

  static const char* ascii_fingerprint; // = "3F5FC93B338687BC7235B1AB103F47B3";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0x5F,0xC9,0x3B,0x33,0x86,0x87,0xBC,0x72,0x35,0xB1,0xAB,0x10,0x3F,0x47,0xB3};

  Bonk() : type(0), message("") {
  }

  virtual ~Bonk() throw() {}

  static apache::thrift::reflection::local::TypeSpec* local_reflection;

  int32_t type;
  std::string message;

  struct __isset {
    __isset() : type(false), message(false) {}
    bool type;
    bool message;
  } __isset;

  bool operator == (const Bonk & rhs) const
  {
    if (!(type == rhs.type))
      return false;
    if (!(message == rhs.message))
      return false;
    return true;
  }
  bool operator != (const Bonk &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Bonk & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

// {1:i32;2:string;}
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_3F5FC93B338687BC7235B1AB103F47B3;

class Nesting {
 public:

  static const char* ascii_fingerprint; // = "9D961D015265DA7A88BA69FB2A7ACDA9";
  static const uint8_t binary_fingerprint[16]; // = {0x9D,0x96,0x1D,0x01,0x52,0x65,0xDA,0x7A,0x88,0xBA,0x69,0xFB,0x2A,0x7A,0xCD,0xA9};

  Nesting() {
  }

  virtual ~Nesting() throw() {}

  static apache::thrift::reflection::local::TypeSpec* local_reflection;

  Bonk my_bonk;
  OneOfEach my_ooe;

  struct __isset {
    __isset() : my_bonk(false), my_ooe(false) {}
    bool my_bonk;
    bool my_ooe;
  } __isset;

  bool operator == (const Nesting & rhs) const
  {
    if (!(my_bonk == rhs.my_bonk))
      return false;
    if (!(my_ooe == rhs.my_ooe))
      return false;
    return true;
  }
  bool operator != (const Nesting &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Nesting & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

// {1:{1:i32;2:string;};2:{1:bool;2:bool;3:byte;4:i16;5:i32;6:i64;7:double;8:string;9:string;10:bool;11:string;12:list<byte>;13:list<i16>;14:list<i64>;};}
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_9D961D015265DA7A88BA69FB2A7ACDA9;

class HolyMoley {
 public:

  static const char* ascii_fingerprint; // = "63B6C93A44D5393BB40AF7623EA1919F";
  static const uint8_t binary_fingerprint[16]; // = {0x63,0xB6,0xC9,0x3A,0x44,0xD5,0x39,0x3B,0xB4,0x0A,0xF7,0x62,0x3E,0xA1,0x91,0x9F};

  HolyMoley() {
  }

  virtual ~HolyMoley() throw() {}

  static apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::vector<OneOfEach>  big;
  std::set<std::vector<std::string> >  contain;
  std::map<std::string, std::vector<Bonk> >  bonks;

  struct __isset {
    __isset() : big(false), contain(false), bonks(false) {}
    bool big;
    bool contain;
    bool bonks;
  } __isset;

  bool operator == (const HolyMoley & rhs) const
  {
    if (!(big == rhs.big))
      return false;
    if (!(contain == rhs.contain))
      return false;
    if (!(bonks == rhs.bonks))
      return false;
    return true;
  }
  bool operator != (const HolyMoley &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HolyMoley & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

// list<{1:bool;2:bool;3:byte;4:i16;5:i32;6:i64;7:double;8:string;9:string;10:bool;11:string;12:list<byte>;13:list<i16>;14:list<i64>;}>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_EFF35C55709151D6F9BA209210A64A9A;

// list<string>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_1F997684D04C8586EA5BDBB510E47233;

// set<list<string>>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_08B77EFB81A30DD0849F03CD371B217F;

// list<{1:i32;2:string;}>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_55CEEE2B7ABA3A0ADE97E724FAFAB31A;

// map<string,list<{1:i32;2:string;}>>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_7D09D9AA976355FEB241190785C6DBFD;

// {1:list<{1:bool;2:bool;3:byte;4:i16;5:i32;6:i64;7:double;8:string;9:string;10:bool;11:string;12:list<byte>;13:list<i16>;14:list<i64>;}>;2:set<list<string>>;3:map<string,list<{1:i32;2:string;}>>;}
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_63B6C93A44D5393BB40AF7623EA1919F;

class Backwards {
 public:

  static const char* ascii_fingerprint; // = "51318B85E029E14809E8DAB5AF9D7E3A";
  static const uint8_t binary_fingerprint[16]; // = {0x51,0x31,0x8B,0x85,0xE0,0x29,0xE1,0x48,0x09,0xE8,0xDA,0xB5,0xAF,0x9D,0x7E,0x3A};

  Backwards() : first_tag2(0), second_tag1(0) {
  }

  virtual ~Backwards() throw() {}

  static apache::thrift::reflection::local::TypeSpec* local_reflection;

  int32_t first_tag2;
  int32_t second_tag1;

  struct __isset {
    __isset() : first_tag2(false), second_tag1(false) {}
    bool first_tag2;
    bool second_tag1;
  } __isset;

  bool operator == (const Backwards & rhs) const
  {
    if (!(first_tag2 == rhs.first_tag2))
      return false;
    if (!(second_tag1 == rhs.second_tag1))
      return false;
    return true;
  }
  bool operator != (const Backwards &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Backwards & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

// {2:i32;1:i32;}
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_51318B85E029E14809E8DAB5AF9D7E3A;

class Empty {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  Empty() {
  }

  virtual ~Empty() throw() {}

  static apache::thrift::reflection::local::TypeSpec* local_reflection;


  bool operator == (const Empty & /* rhs */) const
  {
    return true;
  }
  bool operator != (const Empty &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Empty & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

// {}
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_99914B932BD37A50B983C5E7C90AE93B;

class Wrapper {
 public:

  static const char* ascii_fingerprint; // = "2C32A565725135A023CB591D1A993CFD";
  static const uint8_t binary_fingerprint[16]; // = {0x2C,0x32,0xA5,0x65,0x72,0x51,0x35,0xA0,0x23,0xCB,0x59,0x1D,0x1A,0x99,0x3C,0xFD};

  Wrapper() {
  }

  virtual ~Wrapper() throw() {}

  static apache::thrift::reflection::local::TypeSpec* local_reflection;

  Empty foo;

  struct __isset {
    __isset() : foo(false) {}
    bool foo;
  } __isset;

  bool operator == (const Wrapper & rhs) const
  {
    if (!(foo == rhs.foo))
      return false;
    return true;
  }
  bool operator != (const Wrapper &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Wrapper & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

// {1:{};}
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_2C32A565725135A023CB591D1A993CFD;

class RandomStuff {
 public:

  static const char* ascii_fingerprint; // = "8E3A2E54E7FBB5A4EA75EC85E71FE8BE";
  static const uint8_t binary_fingerprint[16]; // = {0x8E,0x3A,0x2E,0x54,0xE7,0xFB,0xB5,0xA4,0xEA,0x75,0xEC,0x85,0xE7,0x1F,0xE8,0xBE};

  RandomStuff() : a(0), b(0), c(0), d(0), bigint(0), triple(0) {
  }

  virtual ~RandomStuff() throw() {}

  static apache::thrift::reflection::local::TypeSpec* local_reflection;

  int32_t a;
  int32_t b;
  int32_t c;
  int32_t d;
  std::vector<int32_t>  myintlist;
  std::map<int32_t, Wrapper>  maps;
  int64_t bigint;
  double triple;

  struct __isset {
    __isset() : a(false), b(false), c(false), d(false), myintlist(false), maps(false), bigint(false), triple(false) {}
    bool a;
    bool b;
    bool c;
    bool d;
    bool myintlist;
    bool maps;
    bool bigint;
    bool triple;
  } __isset;

  bool operator == (const RandomStuff & rhs) const
  {
    if (!(a == rhs.a))
      return false;
    if (!(b == rhs.b))
      return false;
    if (!(c == rhs.c))
      return false;
    if (!(d == rhs.d))
      return false;
    if (!(myintlist == rhs.myintlist))
      return false;
    if (!(maps == rhs.maps))
      return false;
    if (!(bigint == rhs.bigint))
      return false;
    if (!(triple == rhs.triple))
      return false;
    return true;
  }
  bool operator != (const RandomStuff &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RandomStuff & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

// list<i32>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_088BFAA0A90D491A87F1AA2810C1FC6D;

// map<i32,{1:{};}>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_009536FB14D08A80EAAB3A13751B902E;

// {1:i32;2:i32;3:i32;4:i32;5:list<i32>;6:map<i32,{1:{};}>;7:i64;8:double;}
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_8E3A2E54E7FBB5A4EA75EC85E71FE8BE;

class Base64 {
 public:

  static const char* ascii_fingerprint; // = "D6983CD9C5C18EAC36C957E4BED331AE";
  static const uint8_t binary_fingerprint[16]; // = {0xD6,0x98,0x3C,0xD9,0xC5,0xC1,0x8E,0xAC,0x36,0xC9,0x57,0xE4,0xBE,0xD3,0x31,0xAE};

  Base64() : a(0), b1(""), b2(""), b3(""), b4(""), b5(""), b6("") {
  }

  virtual ~Base64() throw() {}

  static apache::thrift::reflection::local::TypeSpec* local_reflection;

  int32_t a;
  std::string b1;
  std::string b2;
  std::string b3;
  std::string b4;
  std::string b5;
  std::string b6;

  struct __isset {
    __isset() : a(false), b1(false), b2(false), b3(false), b4(false), b5(false), b6(false) {}
    bool a;
    bool b1;
    bool b2;
    bool b3;
    bool b4;
    bool b5;
    bool b6;
  } __isset;

  bool operator == (const Base64 & rhs) const
  {
    if (!(a == rhs.a))
      return false;
    if (!(b1 == rhs.b1))
      return false;
    if (!(b2 == rhs.b2))
      return false;
    if (!(b3 == rhs.b3))
      return false;
    if (!(b4 == rhs.b4))
      return false;
    if (!(b5 == rhs.b5))
      return false;
    if (!(b6 == rhs.b6))
      return false;
    return true;
  }
  bool operator != (const Base64 &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Base64 & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

// {1:i32;2:string;3:string;4:string;5:string;6:string;7:string;}
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_D6983CD9C5C18EAC36C957E4BED331AE;

class BlowUp {
 public:

  static const char* ascii_fingerprint; // = "C31E40A0D0B3CC76A374729E31FB848F";
  static const uint8_t binary_fingerprint[16]; // = {0xC3,0x1E,0x40,0xA0,0xD0,0xB3,0xCC,0x76,0xA3,0x74,0x72,0x9E,0x31,0xFB,0x84,0x8F};

  BlowUp() {
  }

  virtual ~BlowUp() throw() {}

  static apache::thrift::reflection::local::TypeSpec* local_reflection;

  std::map<std::vector<int32_t> , std::set<std::map<int32_t, std::string> > >  b1;
  std::map<std::vector<int32_t> , std::set<std::map<int32_t, std::string> > >  b2;
  std::map<std::vector<int32_t> , std::set<std::map<int32_t, std::string> > >  b3;
  std::map<std::vector<int32_t> , std::set<std::map<int32_t, std::string> > >  b4;

  struct __isset {
    __isset() : b1(false), b2(false), b3(false), b4(false) {}
    bool b1;
    bool b2;
    bool b3;
    bool b4;
  } __isset;

  bool operator == (const BlowUp & rhs) const
  {
    if (!(b1 == rhs.b1))
      return false;
    if (!(b2 == rhs.b2))
      return false;
    if (!(b3 == rhs.b3))
      return false;
    if (!(b4 == rhs.b4))
      return false;
    return true;
  }
  bool operator != (const BlowUp &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const BlowUp & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

// map<i32,string>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_6870A6B6F5D23566138BB497788EDCB9;

// set<map<i32,string>>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_5C11F9C1DEA7D83F0F2A77015750AA37;

// map<list<i32>,set<map<i32,string>>>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_E100D6D4278D9E4BE53BFEF7E58A0B64;

// {1:map<list<i32>,set<map<i32,string>>>;2:map<list<i32>,set<map<i32,string>>>;3:map<list<i32>,set<map<i32,string>>>;4:map<list<i32>,set<map<i32,string>>>;}
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_C31E40A0D0B3CC76A374729E31FB848F;

class CompactProtoTestStruct {
 public:

  static const char* ascii_fingerprint; // = "FECB06442E1E082EBF36FB8CB75EB414";
  static const uint8_t binary_fingerprint[16]; // = {0xFE,0xCB,0x06,0x44,0x2E,0x1E,0x08,0x2E,0xBF,0x36,0xFB,0x8C,0xB7,0x5E,0xB4,0x14};

  CompactProtoTestStruct() : a_byte(127), a_i16(32000), a_i32(1000000000), a_i64(1099511627775LL), a_double(5.6789), a_string("my string"), a_binary(""), true_field(true), false_field(false) {

    byte_list.push_back(-127);
    byte_list.push_back(-1);
    byte_list.push_back(0);
    byte_list.push_back(1);
    byte_list.push_back(127);

    i16_list.push_back(-1);
    i16_list.push_back(0);
    i16_list.push_back(1);
    i16_list.push_back(32767);

    i32_list.push_back(-1);
    i32_list.push_back(0);
    i32_list.push_back(255);
    i32_list.push_back(65535);
    i32_list.push_back(16777215);
    i32_list.push_back(2147483647);

    i64_list.push_back(-1LL);
    i64_list.push_back(0LL);
    i64_list.push_back(255LL);
    i64_list.push_back(65535LL);
    i64_list.push_back(16777215LL);
    i64_list.push_back(4294967295LL);
    i64_list.push_back(1099511627775LL);
    i64_list.push_back(281474976710655LL);
    i64_list.push_back(72057594037927935LL);
    i64_list.push_back(9223372036854775807LL);

    double_list.push_back(0.1);
    double_list.push_back(0.2);
    double_list.push_back(0.3);

    string_list.push_back("first");
    string_list.push_back("second");
    string_list.push_back("third");

    boolean_list.push_back(true);
    boolean_list.push_back(true);
    boolean_list.push_back(true);
    boolean_list.push_back(false);
    boolean_list.push_back(false);
    boolean_list.push_back(false);

    Empty tmp181;

    struct_list.push_back(tmp181);
    Empty tmp182;

    struct_list.push_back(tmp182);

    byte_set.insert(-127);
    byte_set.insert(-1);
    byte_set.insert(0);
    byte_set.insert(1);
    byte_set.insert(127);

    i16_set.insert(-1);
    i16_set.insert(0);
    i16_set.insert(1);
    i16_set.insert(32767);

    i32_set.insert(1);
    i32_set.insert(2);
    i32_set.insert(3);

    i64_set.insert(-1LL);
    i64_set.insert(0LL);
    i64_set.insert(255LL);
    i64_set.insert(65535LL);
    i64_set.insert(16777215LL);
    i64_set.insert(4294967295LL);
    i64_set.insert(1099511627775LL);
    i64_set.insert(281474976710655LL);
    i64_set.insert(72057594037927935LL);
    i64_set.insert(9223372036854775807LL);

    double_set.insert(0.1);
    double_set.insert(0.2);
    double_set.insert(0.3);

    string_set.insert("first");
    string_set.insert("second");
    string_set.insert("third");

    boolean_set.insert(true);
    boolean_set.insert(false);

    Empty tmp183;

    struct_set.insert(tmp183);

    byte_byte_map.insert(std::make_pair(1, 2));

    i16_byte_map.insert(std::make_pair(1, 1));
    i16_byte_map.insert(std::make_pair(-1, 1));
    i16_byte_map.insert(std::make_pair(32767, 1));

    i32_byte_map.insert(std::make_pair(1, 1));
    i32_byte_map.insert(std::make_pair(-1, 1));
    i32_byte_map.insert(std::make_pair(2147483647, 1));

    i64_byte_map.insert(std::make_pair(0LL, 1));
    i64_byte_map.insert(std::make_pair(1LL, 1));
    i64_byte_map.insert(std::make_pair(-1LL, 1));
    i64_byte_map.insert(std::make_pair(9223372036854775807LL, 1));

    double_byte_map.insert(std::make_pair(-1.1, 1));
    double_byte_map.insert(std::make_pair(1.1, 1));

    string_byte_map.insert(std::make_pair("first", 1));
    string_byte_map.insert(std::make_pair("second", 2));
    string_byte_map.insert(std::make_pair("third", 3));
    string_byte_map.insert(std::make_pair("", 0));

    boolean_byte_map.insert(std::make_pair(true, 1));
    boolean_byte_map.insert(std::make_pair(false, 0));

    byte_i16_map.insert(std::make_pair(1, 1));
    byte_i16_map.insert(std::make_pair(2, -1));
    byte_i16_map.insert(std::make_pair(3, 32767));

    byte_i32_map.insert(std::make_pair(1, 1));
    byte_i32_map.insert(std::make_pair(2, -1));
    byte_i32_map.insert(std::make_pair(3, 2147483647));

    byte_i64_map.insert(std::make_pair(1, 1LL));
    byte_i64_map.insert(std::make_pair(2, -1LL));
    byte_i64_map.insert(std::make_pair(3, 9223372036854775807LL));

    byte_double_map.insert(std::make_pair(1, 0.1));
    byte_double_map.insert(std::make_pair(2, -0.1));
    byte_double_map.insert(std::make_pair(3, 1e+06));

    byte_string_map.insert(std::make_pair(1, ""));
    byte_string_map.insert(std::make_pair(2, "blah"));
    byte_string_map.insert(std::make_pair(3, "loooooooooooooong string"));

    byte_boolean_map.insert(std::make_pair(1, true));
    byte_boolean_map.insert(std::make_pair(2, false));

    std::vector<int8_t>  tmp184;
    tmp184.push_back(1);
    tmp184.push_back(2);
    tmp184.push_back(3);

    list_byte_map.insert(std::make_pair(tmp184, 1));
    std::vector<int8_t>  tmp185;
    tmp185.push_back(0);
    tmp185.push_back(1);

    list_byte_map.insert(std::make_pair(tmp185, 2));
    std::vector<int8_t>  tmp186;

    list_byte_map.insert(std::make_pair(tmp186, 0));

    std::set<int8_t>  tmp187;
    tmp187.insert(1);
    tmp187.insert(2);
    tmp187.insert(3);

    set_byte_map.insert(std::make_pair(tmp187, 1));
    std::set<int8_t>  tmp188;
    tmp188.insert(0);
    tmp188.insert(1);

    set_byte_map.insert(std::make_pair(tmp188, 2));
    std::set<int8_t>  tmp189;

    set_byte_map.insert(std::make_pair(tmp189, 0));

    std::map<int8_t, int8_t>  tmp190;
    tmp190.insert(std::make_pair(1, 1));

    map_byte_map.insert(std::make_pair(tmp190, 1));
    std::map<int8_t, int8_t>  tmp191;
    tmp191.insert(std::make_pair(2, 2));

    map_byte_map.insert(std::make_pair(tmp191, 2));
    std::map<int8_t, int8_t>  tmp192;

    map_byte_map.insert(std::make_pair(tmp192, 0));

    std::map<int8_t, int8_t>  tmp193;

    byte_map_map.insert(std::make_pair(0, tmp193));
    std::map<int8_t, int8_t>  tmp194;
    tmp194.insert(std::make_pair(1, 1));

    byte_map_map.insert(std::make_pair(1, tmp194));
    std::map<int8_t, int8_t>  tmp195;
    tmp195.insert(std::make_pair(1, 1));
    tmp195.insert(std::make_pair(2, 2));

    byte_map_map.insert(std::make_pair(2, tmp195));

    std::set<int8_t>  tmp196;

    byte_set_map.insert(std::make_pair(0, tmp196));
    std::set<int8_t>  tmp197;
    tmp197.insert(1);

    byte_set_map.insert(std::make_pair(1, tmp197));
    std::set<int8_t>  tmp198;
    tmp198.insert(1);
    tmp198.insert(2);

    byte_set_map.insert(std::make_pair(2, tmp198));

    std::vector<int8_t>  tmp199;

    byte_list_map.insert(std::make_pair(0, tmp199));
    std::vector<int8_t>  tmp200;
    tmp200.push_back(1);

    byte_list_map.insert(std::make_pair(1, tmp200));
    std::vector<int8_t>  tmp201;
    tmp201.push_back(1);
    tmp201.push_back(2);

    byte_list_map.insert(std::make_pair(2, tmp201));

  }

  virtual ~CompactProtoTestStruct() throw() {}

  static apache::thrift::reflection::local::TypeSpec* local_reflection;

  int8_t a_byte;
  int16_t a_i16;
  int32_t a_i32;
  int64_t a_i64;
  double a_double;
  std::string a_string;
  std::string a_binary;
  bool true_field;
  bool false_field;
  Empty empty_struct_field;
  std::vector<int8_t>  byte_list;
  std::vector<int16_t>  i16_list;
  std::vector<int32_t>  i32_list;
  std::vector<int64_t>  i64_list;
  std::vector<double>  double_list;
  std::vector<std::string>  string_list;
  std::vector<std::string>  binary_list;
  std::vector<bool>  boolean_list;
  std::vector<Empty>  struct_list;
  std::set<int8_t>  byte_set;
  std::set<int16_t>  i16_set;
  std::set<int32_t>  i32_set;
  std::set<int64_t>  i64_set;
  std::set<double>  double_set;
  std::set<std::string>  string_set;
  std::set<std::string>  binary_set;
  std::set<bool>  boolean_set;
  std::set<Empty>  struct_set;
  std::map<int8_t, int8_t>  byte_byte_map;
  std::map<int16_t, int8_t>  i16_byte_map;
  std::map<int32_t, int8_t>  i32_byte_map;
  std::map<int64_t, int8_t>  i64_byte_map;
  std::map<double, int8_t>  double_byte_map;
  std::map<std::string, int8_t>  string_byte_map;
  std::map<std::string, int8_t>  binary_byte_map;
  std::map<bool, int8_t>  boolean_byte_map;
  std::map<int8_t, int16_t>  byte_i16_map;
  std::map<int8_t, int32_t>  byte_i32_map;
  std::map<int8_t, int64_t>  byte_i64_map;
  std::map<int8_t, double>  byte_double_map;
  std::map<int8_t, std::string>  byte_string_map;
  std::map<int8_t, std::string>  byte_binary_map;
  std::map<int8_t, bool>  byte_boolean_map;
  std::map<std::vector<int8_t> , int8_t>  list_byte_map;
  std::map<std::set<int8_t> , int8_t>  set_byte_map;
  std::map<std::map<int8_t, int8_t> , int8_t>  map_byte_map;
  std::map<int8_t, std::map<int8_t, int8_t> >  byte_map_map;
  std::map<int8_t, std::set<int8_t> >  byte_set_map;
  std::map<int8_t, std::vector<int8_t> >  byte_list_map;

  struct __isset {
    __isset() : a_byte(false), a_i16(false), a_i32(false), a_i64(false), a_double(false), a_string(false), a_binary(false), true_field(false), false_field(false), empty_struct_field(false), byte_list(false), i16_list(false), i32_list(false), i64_list(false), double_list(false), string_list(false), binary_list(false), boolean_list(false), struct_list(false), byte_set(false), i16_set(false), i32_set(false), i64_set(false), double_set(false), string_set(false), binary_set(false), boolean_set(false), struct_set(false), byte_byte_map(false), i16_byte_map(false), i32_byte_map(false), i64_byte_map(false), double_byte_map(false), string_byte_map(false), binary_byte_map(false), boolean_byte_map(false), byte_i16_map(false), byte_i32_map(false), byte_i64_map(false), byte_double_map(false), byte_string_map(false), byte_binary_map(false), byte_boolean_map(false), list_byte_map(false), set_byte_map(false), map_byte_map(false), byte_map_map(false), byte_set_map(false), byte_list_map(false) {}
    bool a_byte;
    bool a_i16;
    bool a_i32;
    bool a_i64;
    bool a_double;
    bool a_string;
    bool a_binary;
    bool true_field;
    bool false_field;
    bool empty_struct_field;
    bool byte_list;
    bool i16_list;
    bool i32_list;
    bool i64_list;
    bool double_list;
    bool string_list;
    bool binary_list;
    bool boolean_list;
    bool struct_list;
    bool byte_set;
    bool i16_set;
    bool i32_set;
    bool i64_set;
    bool double_set;
    bool string_set;
    bool binary_set;
    bool boolean_set;
    bool struct_set;
    bool byte_byte_map;
    bool i16_byte_map;
    bool i32_byte_map;
    bool i64_byte_map;
    bool double_byte_map;
    bool string_byte_map;
    bool binary_byte_map;
    bool boolean_byte_map;
    bool byte_i16_map;
    bool byte_i32_map;
    bool byte_i64_map;
    bool byte_double_map;
    bool byte_string_map;
    bool byte_binary_map;
    bool byte_boolean_map;
    bool list_byte_map;
    bool set_byte_map;
    bool map_byte_map;
    bool byte_map_map;
    bool byte_set_map;
    bool byte_list_map;
  } __isset;

  bool operator == (const CompactProtoTestStruct & rhs) const
  {
    if (!(a_byte == rhs.a_byte))
      return false;
    if (!(a_i16 == rhs.a_i16))
      return false;
    if (!(a_i32 == rhs.a_i32))
      return false;
    if (!(a_i64 == rhs.a_i64))
      return false;
    if (!(a_double == rhs.a_double))
      return false;
    if (!(a_string == rhs.a_string))
      return false;
    if (!(a_binary == rhs.a_binary))
      return false;
    if (!(true_field == rhs.true_field))
      return false;
    if (!(false_field == rhs.false_field))
      return false;
    if (!(empty_struct_field == rhs.empty_struct_field))
      return false;
    if (!(byte_list == rhs.byte_list))
      return false;
    if (!(i16_list == rhs.i16_list))
      return false;
    if (!(i32_list == rhs.i32_list))
      return false;
    if (!(i64_list == rhs.i64_list))
      return false;
    if (!(double_list == rhs.double_list))
      return false;
    if (!(string_list == rhs.string_list))
      return false;
    if (!(binary_list == rhs.binary_list))
      return false;
    if (!(boolean_list == rhs.boolean_list))
      return false;
    if (!(struct_list == rhs.struct_list))
      return false;
    if (!(byte_set == rhs.byte_set))
      return false;
    if (!(i16_set == rhs.i16_set))
      return false;
    if (!(i32_set == rhs.i32_set))
      return false;
    if (!(i64_set == rhs.i64_set))
      return false;
    if (!(double_set == rhs.double_set))
      return false;
    if (!(string_set == rhs.string_set))
      return false;
    if (!(binary_set == rhs.binary_set))
      return false;
    if (!(boolean_set == rhs.boolean_set))
      return false;
    if (!(struct_set == rhs.struct_set))
      return false;
    if (!(byte_byte_map == rhs.byte_byte_map))
      return false;
    if (!(i16_byte_map == rhs.i16_byte_map))
      return false;
    if (!(i32_byte_map == rhs.i32_byte_map))
      return false;
    if (!(i64_byte_map == rhs.i64_byte_map))
      return false;
    if (!(double_byte_map == rhs.double_byte_map))
      return false;
    if (!(string_byte_map == rhs.string_byte_map))
      return false;
    if (!(binary_byte_map == rhs.binary_byte_map))
      return false;
    if (!(boolean_byte_map == rhs.boolean_byte_map))
      return false;
    if (!(byte_i16_map == rhs.byte_i16_map))
      return false;
    if (!(byte_i32_map == rhs.byte_i32_map))
      return false;
    if (!(byte_i64_map == rhs.byte_i64_map))
      return false;
    if (!(byte_double_map == rhs.byte_double_map))
      return false;
    if (!(byte_string_map == rhs.byte_string_map))
      return false;
    if (!(byte_binary_map == rhs.byte_binary_map))
      return false;
    if (!(byte_boolean_map == rhs.byte_boolean_map))
      return false;
    if (!(list_byte_map == rhs.list_byte_map))
      return false;
    if (!(set_byte_map == rhs.set_byte_map))
      return false;
    if (!(map_byte_map == rhs.map_byte_map))
      return false;
    if (!(byte_map_map == rhs.byte_map_map))
      return false;
    if (!(byte_set_map == rhs.byte_set_map))
      return false;
    if (!(byte_list_map == rhs.byte_list_map))
      return false;
    return true;
  }
  bool operator != (const CompactProtoTestStruct &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const CompactProtoTestStruct & ) const;

  uint32_t read(apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(apache::thrift::protocol::TProtocol* oprot) const;

};

// list<double>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_D6AEC7E93315AED6C2F228E4A906D442;

// list<bool>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_8E94B3B8D6C11F11416F407E0E5DD645;

// list<{}>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_FC89DC9CFCE2B64549D834C7D524F4CE;

// set<byte>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_941851E0D30D43A865F9A5B45701B485;

// set<i16>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_D0694DB62562D95D51BB12FCE742233F;

// set<i32>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_698CD5CC80596EF059310FAB605A4491;

// set<i64>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_6B9CCE9D3F24C3B56F679700AFE6F569;

// set<double>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_A57192399D0FE7565A6242260B4B2ED9;

// set<string>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_5B34865E3E09883456AB4096E5B3127A;

// set<bool>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_01323420E628F4ADC6BA7DFCB543CB0F;

// set<{}>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_21AD9E158C2172DB8799B91CD0E52582;

// map<byte,byte>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_92564D937E550F7CFDB650B571A4721C;

// map<i16,byte>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_171296C3BC146F62A7BA3343CA4EE758;

// map<i32,byte>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_AFB1B3ECD0A07CC6C181869B1A2FA60A;

// map<i64,byte>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_06818F6175A3915CF8C618F32212A451;

// map<double,byte>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_E0E210CDABA8A38A3EFA5214AE908496;

// map<string,byte>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_0D41768A12E3890E6FA94FED8184946D;

// map<bool,byte>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_A31ED0D47760FB26F56B4CCED43DA5EC;

// map<byte,i16>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_7C401D81BFB7A48121223E01303FC373;

// map<byte,i32>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_4B357CAA02423DEDB92F0D36BCB994B9;

// map<byte,i64>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_0C98DBB2DAB76A3702A0B4820E4800DD;

// map<byte,double>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_228302BAFBF208C0A6C8F204B88DB3E1;

// map<byte,string>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_BCDB1ABE8E71253720DC2E61CE96CF04;

// map<byte,bool>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_0A366525281FF13F319B1A7276C975DF;

// map<list<byte>,byte>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_2AAE00BD36DB5899F2AA576353932BA2;

// map<set<byte>,byte>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_8D6630E2281DCBB1D8BC2FD6D0347B36;

// map<map<byte,byte>,byte>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_8FF964EDC3CA1DB6C9EC28BF1836A5D2;

// map<byte,map<byte,byte>>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_C5BAEF94D938920BAAA1E4C93709AF82;

// map<byte,set<byte>>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_684A6B988F32DBF57C6A1546CF441F21;

// map<byte,list<byte>>
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_E65AA5DC61F5EDBA963EB105CE3F813A;

// {1:byte;2:i16;3:i32;4:i64;5:double;6:string;7:string;8:bool;9:bool;10:{};11:list<byte>;12:list<i16>;13:list<i32>;14:list<i64>;15:list<double>;16:list<string>;17:list<string>;18:list<bool>;19:list<{}>;20:set<byte>;21:set<i16>;22:set<i32>;23:set<i64>;24:set<double>;25:set<string>;26:set<string>;27:set<bool>;28:set<{}>;29:map<byte,byte>;30:map<i16,byte>;31:map<i32,byte>;32:map<i64,byte>;33:map<double,byte>;34:map<string,byte>;35:map<string,byte>;36:map<bool,byte>;37:map<byte,i16>;38:map<byte,i32>;39:map<byte,i64>;40:map<byte,double>;41:map<byte,string>;42:map<byte,string>;43:map<byte,bool>;44:map<list<byte>,byte>;45:map<set<byte>,byte>;46:map<map<byte,byte>,byte>;47:map<byte,map<byte,byte>>;48:map<byte,set<byte>>;49:map<byte,list<byte>>;}
extern apache::thrift::reflection::local::TypeSpec
trlo_typespec_DebugProtoTest_FECB06442E1E082EBF36FB8CB75EB414;

}}} // namespace

#endif
