/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "StressTest_types.h"

#include <TReflectionLocal.h>

namespace test { namespace stress {

}} // namespace
