/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "ThriftTest_constants.h"

namespace thrift { namespace test {

const ThriftTestConstants g_ThriftTest_constants;

ThriftTestConstants::ThriftTestConstants() {
}

}} // namespace

